<?php
$jsonflex=
[
  "type"=>"flex",
  "altText"=>"Flex Message",
  "contents"=>[
    "type"=>"bubble",
    "direction"=>"ltr",
    "body"=>[
      "type"=>"box",
      "layout"=>"vertical",
      "spacing"=>"md",
      "action"=>[
        "type"=>"uri",
        "label"=>"Action",
        "uri"=>"https://linecorp.com"
      ],
      "contents"=>[
        [
          "type"=>"text",
          "text"=>$row["name"],
          "size"=>"lg",
          "weight"=>"bold",
          "color"=>"#000000",
          "wrap"=>true
        ],
        [
          "type"=>"separator",
          "color"=>"#FD4C00"
        ],
        [
          "type"=>"box",
          "layout"=>"vertical",
          "spacing"=>"sm",
          "contents"=>[
            [
              "type"=>"box",
              "layout"=>"baseline",
              "contents"=>[
                [
                  "type"=>"icon",
                  "url"=>"https://sv1.picz.in.th/images/2020/01/25/R8cQkW.jpg",
                  "size"=>"xl"
                ],
                [
                  "type"=>"text",
                  "text"=>"มีสินค้าจำนวนดังนี้",
                  "flex"=>0,
                  "margin"=>"sm",
                  "size"=>"sm",
                  "weight"=>"regular",
                  "color"=>"#37474F"
                ],
                [
                  "type"=>"text",
                  "text"=>$row["s_size"],
                  "size"=>"sm",
                  "align"=>"end",
                  "weight"=>"bold",
                  "color"=>"#000000"
                ],
                [
                  "type"=>"text",
                  "text"=>"  ตัว",
                  "margin"=>"md",
                  "color"=>"#37474F"
                ]
              ]
            ],
            [
              "type"=>"box",
              "layout"=>"baseline",
              "contents"=>[
                [
                  "type"=>"icon",
                  "url"=>"https://sv1.picz.in.th/images/2020/01/25/R8gnvW.jpg",
                  "size"=>"xl"
                ],
                [
                  "type"=>"text",
                  "text"=>"มีสินค้าจำนวนดังนี้",
                  "flex"=>0,
                  "margin"=>"sm",
                  "size"=>"sm",
                  "weight"=>"regular",
                  "color"=>"#37474F"
                ],
                [
                  "type"=>"text",
                  "text"=>$row["m_size"],
                  "size"=>"sm",
                  "align"=>"end",
                  "weight"=>"bold",
                  "color"=>"#000000"
                ],
                [
                  "type"=>"text",
                  "text"=>"  ตัว",
                  "margin"=>"md",
                  "color"=>"#37474F"
                ]
              ]
            ],
            [
              "type"=>"box",
              "layout"=>"baseline",
              "contents"=>[
                [
                  "type"=>"icon",
                  "url"=>"https://sv1.picz.in.th/images/2020/01/25/R8gHU1.jpg",
                  "size"=>"xl"
                ],
                [
                  "type"=>"text",
                  "text"=>"มีสินค้าจำนวนดังนี้",
                  "flex"=>0,
                  "margin"=>"sm",
                  "size"=>"sm",
                  "weight"=>"regular",
                  "color"=>"#37474F"
                ],
                [
                  "type"=>"text",
                  "text"=>$row["l_size"],
                  "size"=>"sm",
                  "align"=>"end",
                  "weight"=>"bold",
                  "color"=>"#000000"
                ],
                [
                  "type"=>"text",
                  "text"=>"  ตัว",
                  "margin"=>"md",
                  "color"=>"#37474F"
                ]
              ]
            ],
            [
              "type"=>"box",
              "layout"=>"baseline",
              "contents"=>[
                [
                  "type"=>"icon",
                  "url"=>"https://sv1.picz.in.th/images/2020/01/25/R8ga0D.jpg",
                  "size"=>"xl"
                ],
                [
                  "type"=>"text",
                  "text"=>"มีสินค้าจำนวนดังนี้",
                  "flex"=>0,
                  "margin"=>"sm",
                  "size"=>"sm",
                  "weight"=>"regular",
                  "color"=>"#37474F"
                ],
                [
                  "type"=>"text",
                  "text"=>$row["xl_size"],
                  "size"=>"sm",
                  "align"=>"end",
                  "weight"=>"bold",
                  "color"=>"#000000"
                ],
                [
                  "type"=>"text",
                  "text"=>"  ตัว",
                  "margin"=>"md",
                  "color"=>"#37474F"
                ]
              ]
            ]
          ]
        ],
        [
          "type"=>"separator",
          "margin"=>"xs",
          "color"=>"#FD4C00"
        ]
      ]
    ],
    "footer"=>[
      "type"=>"box",
      "layout"=>"vertical",
      "contents"=>[
        [
          "type"=>"text",
          "text"=>"*สามารถกดปุ่ม Contact us เพื่อติดต่อสั่งซื้อสินค้าหรือกดปุ่ม Follow เพื่อรอรับโปรโมชั่นพิเศษสำหรับคุณลูกค้า",
          "margin"=>"xs",
          "size"=>"xs",
          "align"=>"center",
          "color"=>"#37474F",
          "wrap"=>true
        ],
        [
          "type"=>"box",
          "layout"=>"horizontal",
          "margin"=>"md",
          "contents"=>[
            [
              "type"=>"button",
              "action"=>[
                "type"=>"message",
                "label"=>"Follow",
                "text"=>"Follow : $message[1]"
              ],
              "color"=>"#FF5000",
              "margin"=>"md",
              "style"=>"link"
            ],
            [
              "type"=>"button",
              "action"=>[
                "type"=>"message",
                "label"=>"Contact us",
                "text"=>"Contact us"
              ],
              "color"=>"#FF5000",
              "margin"=>"md",
              "style"=>"primary"
            ]
          ]
        ]
      ]
    ]
  ]
]
?>